version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "miniconda3-4.7"

sphinx:
  configuration: source/conf.py
  fail_on_warning: true

conda:
  environment: environment.yaml

formats:
  - pdf

python:
  install:
  - requirements: source/requirements.txt