---
# readthedocs configuration file
version: 2

python:
  version: "3.11"
  install:
    - requirements: docs/requirements.txt
    - method: pip
    path: .

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

conda:
  file: environment.yaml

formats:
  - pdf