version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

formats:
  - pdf

python:
  install:
  - requirements: docs/requirements.txt

python: 
  install:
  - method: pip
    path: .
    extra_requirements:
      -  source/psyface.py
      -  source/psyfaceutils.py