---
# readthedocs configuration file
version: 2

python:
  version: "3.11"

install:
  - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py

conda:
  file: environment.yaml

formats:
  - "html"
  - "pdf"