version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

sphinx:
  configuration: source/conf.py
  fail_on_warning: true

formats:
  - pdf

python:
  install:
  - requirements: source/requirements.txt